{{- if .Values.appSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.environment }}-{{ include "community-backend.fullname" . }}
  labels:
    {{- include "community-backend.labels" . | nindent 4 }}
type: Opaque
data:
  RECAPTCHA_SECRET: {{ .Values.app.secrets.recaptchaSecret | b64enc | quote }}
  COMMUNITY_PRIV_KEY: {{ .Values.app.secrets.communityPrivKey | b64enc | quote }}
  DATABASE_USERNAME: {{ .Values.app.secrets.dbUsername | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.app.secrets.dbPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.app.secrets.jwtSecret | b64enc | quote }}
  KYC_API_TOKEN: {{ .Values.app.secrets.kycApiToken | b64enc | quote }}
  KYC_API_SECRET: {{ .Values.app.secrets.kycApiSecret | b64enc | quote }}
  SENDGRID_API_KEY: {{ .Values.app.secrets.sendgridApiKey | b64enc | quote }}
  SERVICE_ACCOUNT:  {{ .Values.app.secrets.serviceAccount | b64enc | quote }}
{{- end }} 