{{- if .Values.appSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "community.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ .Values.ingress.auth.secret | quote }}
{{- end }} 